
spring:
   profiles:
      active:
      - dev
      
---
spring:
   profiles: dev
   application:
      name: provide
foo: aaa-dev
      
---
spring:
   profiles: test
   application:
      name: provide-test
foo: aaa-test



